@startuml
object "CharacterPropertiesFactory" as factory {
    flyweights = [
        "Arial16Black" = (Arial, Black, 16),
        "Arial14Black" = (Arial, Black, 14),
        "Verdana18Blue" = (Verdana, Blue, 18),
        "Verdana12Red" = (Verdana, Red, 12),
        "Calibri99Blue" = (Calibri, Blue, 99)
    ]
}

object "Document" as document {
    characters = [
        (H, Calibri, Blue, 99),
        (e, Arial, Black, 14),
        (l, Arial, Black, 14),
        (l, Arial, Black, 14),
        (o, Arial, Black, 14),
        (W, Calibri, Blue, 99),
        (o, Arial, Black, 14),
        (r, Arial, Black, 14),
        (l, Arial, Black, 14),
        (d, Arial, Black, 14),
        (C, Verdana, Blue, 18),
        (S, Verdana, Blue, 18),
        (5, Verdana, Red, 12),
        (8, Verdana, Red, 12),
        (0, Verdana, Red, 12),
        (0, Verdana, Red, 12)
    ]
}

document ..> factory

@enduml